import type { Metadata, Viewport } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";

// const geistSans = Geist({
// 	variable: "--font-geist-sans",
// 	subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
// 	variable: "--font-geist-mono",
// 	subsets: ["latin"],
// });

const montserrat = Montserrat({
	variable: "--font-montserrat",
	subsets: ["latin"],
	weight: ["500"],
});

// ✅ Use Next.js Metadata API for Open Graph tags
export const metadata: Metadata = {
	title: "LazarDesigns Shop",
	description: "Generated by create next app",
	openGraph: {
		type: "website",
		url: "https://lazardesignshops.vercel.app/",
		title: "Home | Lazar Design Shop",
		description: "A short description of this page.",
		images: [
			{
				url: "/LazarDesign.banner.png", // ✅ Use a relative path if stored in /public
				width: 1200,
				height: 630,
				alt: "Lazar Design Shop Banner",
			},
		],
	},
	twitter: {
		card: "summary_large_image",
		title: "Home | Lazar Design Shop",
		description: "A short description of this page.",
		images: ["/LazarDesign.banner.png"], // ✅ Same as OpenGraph image
	},
};

export const viewport: Viewport = {
	themeColor: "#14459E",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${montserrat.variable} antialiased bg-[#FCF5EE] text-black`}
			>
				<Suspense>{children}</Suspense>
			</body>
		</html>
	);
}
