import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Lazar Design Shop",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<Head>
				<meta property="og:type" content="website" />
				<meta
					property="og:url"
					content="https://lazardesignshops.vercel.app/"
				/>
				<meta property="og:title" content="Home | Your Website" />
				<meta
					property="og:description"
					content="A short description of this page."
				/>
				<meta
					property="og:image"
					content="https://lazardesignshops.vercel.app/LazarDesign.banner.png"
				/>
				<meta property="og:image:width" content="1200" />
				<meta property="og:image:height" content="630" />
			</Head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black`}
			>
				{children}
			</body>
		</html>
	);
}
